user/routes.py
import os
import secrets
from itertools import product



from flask import render_template, url_for, flash, redirect, request, Blueprint
from unwrap import app, db, bcrypt
from unwrap.user.models import Products,User,Cart
from unwrap.user.forms import RegistrationForm, LoginForm,UpdateAccountForm
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import func, update

user_bp=Blueprint('user',__name__,template_folder='templates',static_folder='static',static_url_path="/user/static")


def getLoginDetails():
   if current_user.is_authenticated:
       noOfItems=Cart.query.filter_by(buyer=current_user).count()
   else:
       noOfItems=0
   return noOfItems



@user_bp.route("/")
@user_bp.route("/home")
def home():
    return render_template("home.html")

@user_bp.route("/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
      return redirect(url_for("user.home"))
  form=RegistrationForm()
  if form.validate_on_submit():
      try:
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user=User(firstname=form.firstname.data,lastname=form.lastname.data,password=hashed_password,
                email=form.email.data)
        #ic(user)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created","success")
        return redirect(url_for("user.login"))

      except Exception as e:
          print(e)
          flash("Something wrong!", "danger")
          db.session.rollback()
          return redirect(url_for("user.register"))

      finally:
          db.session.close()

  return render_template("register.html",form=form)

@user_bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("user.home"))
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            return redirect(url_for("user.home"))
        else:
            flash("Please check your username and password","danger")

    return render_template("login.html",form=form,noOfItems=getLoginDetails())


@user_bp.route("/logout")
@login_required
def logout():
   logout_user()
   return redirect(url_for("user.home"))

@user_bp.route("/account", methods=['GET', 'POST'])
@login_required
def account():
  form=UpdateAccountForm()
  if form.validate_on_submit():
      current_user.firstname=form.firstname.data
      current_user.lastname = form.lastname.data
      current_user.email = form.email.data
      db.session.commit()
      flash("Update success!!","success")
      return redirect(url_for("account"))
  elif request.method == "GET":
      form.firstname.data=current_user.firstname
      form.lastname.data=current_user.lastname
      form.email.data=current_user.email

  return render_template("account.html",form=form,noOfItems=getLoginDetails())


@user_bp.route("/unwrap-project")
def unwrap_project():
   return render_template("unwrap-project.html")


@user_bp.route("/how-it-works")
def how_it_works():
     pass


@user_bp.route("/select_products", methods=['GET', 'POST'])
def select_products():
    products=Products.query.all()
    return render_template("select_products.html",products=products,noOfItems=getLoginDetails())



@user_bp.route("/addToCart/<int:product_id>")
@login_required
def addToCart(product_id):
  #商品已经在购物车内了，商品数量+1
  row=Cart.query.filter_by(product_id=product_id,buyer=current_user).first()

  if row:
      row.quantity +=1
      db.session.commit()
      flash("This item is already in the cart! Qyt+1!","success")
  # 商品不在购物车内，添加该商品
  else:
      user=User.query.get(current_user.id)
      user.add_to_cart(product_id)

  return redirect(url_for("user.select_products"))





@user_bp.route("/cart", methods=["GET", "POST"])
@login_required
def cart():

     #Products.id, Cart.quantity, Products.price ,Products.name
    cart= (Products.query.join(Cart)
           .add_columns(Cart.quantity,
                        Products.price, Products.name,
                        Products.id).filter_by(buyer=current_user).all())
    subtotal=0
    for item in cart:
        subtotal+= int(item.price)*int(item.quantity)

    if request.method== "POST":
        qty=request.form.get("qty")
        idpd=request.form.get("idpd")
        cartitem=Cart.query.filter_by(product_id=idpd).first()
        cartitem.quantity=qty
        db.session.commit()
        cart = (Products.query.join(Cart)
                .add_columns(Cart.quantity,
                             Products.price, Products.name,
                             Products.id).filter_by(buyer=current_user).all())
        subtotal = 0
        for item in cart:
            subtotal += int(item.price) * int(item.quantity)


    return render_template("cart.html",cart=cart,subtotal=subtotal,noOfItems=getLoginDetails())



@user_bp.route("/removeFromCart/<int:product_id>")
@login_required
def removeFromCart(product_id):
    item_to_remove=Cart.query.filter_by(product_id=product_id).first()
    db.session.delete(item_to_remove)
    db.session.commit()
    flash("Your item has been removed","success")
    return redirect(url_for("user.cart"))

user/templates/account.html
{% extends "layout.html" %}
{% block content %}

      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.firstname }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data" class="form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.firstname.label(class="form-control-label") }}

                    {% if form.firstname.errors %}
                        {{ form.firstname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.firstname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.firstname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.lastname.label(class="form-control-label") }}

                    {% if form.lastname.errors %}
                        {{ form.lastname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.lastname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.lastname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

{% endblock content %}

user/templates/cart.html
{% extends "layout.html" %}
{% block content %}
    <!-- <h1>Your cart</h1> -->
    <!-- <p>Your cart is currently empty.</p> -->
    <!-- <a href="{{ url_for('home') }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">CONTINUE SHOPPING</a> -->
<div id="cartItems">
	<h2>Shopping Cart</h2>


	{% if not cart %}
	
	<p>Your cart is currently empty.</p>
    <a href="{{ url_for('user.select_products') }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">CONTINUE SHOPPING</a>

	{% else %}
		<div style=" text-align: right;">Price</div>
		<div id="tableItems" >

			{% for item in cart %}
			
				<hr>
				<div id="itemName" style=" text-align: 	left;">
					<img src="/static/product{{ item.id }}.JPG" class="card-img-top" alt="..." style="height: 80px; width:80px">
					<span id="itemNameTag">{{item.name}}</span>

					<span id="itemNameTag"><div style=" text-align: right">${{item.price}}</div></span>

				    <form action="{{ url_for('cart') }}" method="post">
    					<div class="form-group">
        
    

	        				<input type="hidden" name="idpd" value="{{item.id}}"/>
						    <select class="form-control" id="exampleFormControlSelect1" style="width:70px; height: 30px" name="qty">
						      <option disabled="Quantity">Qty</option>
						      <option selected="QtyinCart">{{item.quantity}}</option>
						      <option>1</option>
						      <option>2</option>
						      <option>3</option>
						      <option>4</option>
						      <option>5</option>
						    </select>

						    <button class="btn btn-primary" type="submit">Update</button>

							<a href="/removeFromCart/{{item.id}}">Delete</a>
						</div>
					</form>
				</div>

			{% endfor %}
			<hr>
			<div id="total" style=" text-align: right">
				<span id="subtotal">Subtotal: ${{subtotal}}</span>
			</div>
		</div>
	{% endif %}
</div>
<!-- <a href="/checkout">Proceed to checkout</a> -->
{% endblock content %}

user/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="height: 450px">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ url_for('user.static', filename='pic3b.JPG') }}" class="d-block w-100" alt="..." >
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('user.static', filename='pic4b.JPG') }}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('user.static', filename='pic6b.JPG') }}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron">
  <h1 class="display-4">Let's refill!</h1>
  <p class="lead">Plastic is toxic and barely recyclable. At Unwrap LA, we do our best to limit waste and promote local sustainable businesses.</p>
  <!-- <hr class="my-4"> -->
  
</div>

  <div class="container">
    <div class="row">
      <div class="col-md">
        <img src="{{ url_for('user.static', filename='pic7.JPG') }}" class="d-block w-100" alt="...">
      </div>
      <div class="col-md">
        <h1>Personal care and cleaning set</h1>
        <p>$40.00</p>
        <form>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputDelivArea">Delivery Area</label>
              <select id="inputDelivArea" class="form-control">
                <option selected>Choose...</option>
                <option>Beverly Hills</option>
                <option>Santa Monica</option>
                <option>Westwood</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="inputSize">Size</label>
              <select id="inputSize" class="form-control">
                <option selected>Small</option>
                <option>Medium</option>
                <option>Large</option>
              </select>
            </div>
          </div>
          <h2>Subscribe!</h2>
          <p>1 Clean Kit every month</p>
          <button type="submit" class="btn btn-primary">Select your products here!</button>
        </form>
      </div>
    </div>
  </div>

  <div class="jumbotron" >
    <div class="row">
      <h2 class="display-4">FLEXIBILITY + OPTIMIZATION</h2>
      <h4>BOTH PLASTIC PRODUCTION AND CARBON FOOTPRINT COUNT SO LET'S OPTIMIZE. </h4>
      <h4>GET 6 DIFFERENT PRODUCTS AND BRANDS IN ONLY ONE FREE DELIVERY.</h4>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h2>One size containers</h2>
        <p>Our bottles are all the same (16 oz glass bottles). This limits containers production and allows flexibility. Test our products with a small size kit.</p>
      </div>
      <div class="col-sm">
        <h2>Adjust quantity</h2>
        <p>Pick a kit size based on the size of your household and on your own consumption. Don't wait to be completely out of product to get refilled.</p>
      </div>
      <div class="col-sm">
        <h2>Customize your kit</h2>
        <p>You can switch one product to another. Plus, add other products to your delivery. Just go to your cart and continue shopping.</p>
      </div>
    </div>
  </div>

{% endblock content %}

user/templates/how-it-works.html
{% extends "layout.html" %}
{% block content %}

    <h1>How it works</h1>

{% endblock content %}

user/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('user.static',filename='css/bootstrap.css') }}">

    

<!--for glyphicons-->
    <link rel="stylesheet" href="{{ url_for('user.static',filename='css/341/css/bootstrap.css') }}">
    <script src="{{ url_for('user.static',filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('user.static',filename='js/341/bootstrap.js') }}"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('user.static', filename='main.css') }}">


    {% if title %}
        <title>Unwrap - {{ title }}</title>
    {% else %}
        <title>Unwrap</title>
    {% endif %}
</head>
<body >
    <header class="site-header">
      <nav class="navbar  navbar-expand-md navbar-light fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">
            <img id="logo" alt="Logo" src= "{{ url_for('user.static', filename='logo2.JPG') }}"  />
          </a>

          <div class="collapse navbar-collapse" id="navbarToggle" >
            <div class="navbar-nav mr-auto" >
              <a class="nav-item nav-link" href="{{ url_for('user.unwrap_project') }}">The project</a>
              <a class="nav-item nav-link" href="{{ url_for('user.home') }}">Subscription</a>
              <a class="nav-item nav-link" href="{{ url_for('user.select_products') }}">Products</a>
              <!-- <a class="nav-link" href="{{ url_for('user.how_it_works') }}">How it works</a> -->

            </div>

            <!-- Navbar Right Side -->
          </div>
            <div class="navbar-nav nostack" style="display: inline;">
              {% if current_user.is_authenticated %}

              <a class="nav-item nav-link" href="{{ url_for('user.cart') }}" ><span class="glyphicon glyphicon-shopping-cart" id="cartitems" ></span></a>

              <small id="noOfItems">{{noOfItems}}</small>
              <a class="nav-item nav-link" href="{{ url_for('user.account') }}"><span class="glyphicon glyphicon-user" ></span></a>
              <a class="nav-item nav-link" href="{{ url_for('user.logout') }}"><span class="glyphicon glyphicon-log-out" ></span></a>

              {% else %}

                  <a class="nav-item nav-link" href="{{ url_for('user.login') }}" ><span class="glyphicon glyphicon-user" ></span></a>
                 <a class="nav-item nav-link" href="{{ url_for('user.cart') }}"  ><span class="glyphicon glyphicon-shopping-cart"></span></a>

              {% endif %}
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <!-- <div class="row"> -->
        <!-- <div class="col-md-12"> -->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        <!-- </div> -->
      <!-- </div> -->
    </main>
      <footer >
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <h5 class="card-title"><b>Quick Links</b></h5>
              <p class="card-text">Contact Us</p>
              <p class="card-text">Blog</p>
            </div>
            <div class="col-sm-4">
              <h5 class="card-title"><b>Terms and Conditions</b></h5>
              <p class="card-text">Please read our <span><a href="..">terms and conditions here.</a></span></p>
            </div>
            <div class="col-sm-4">
              <h5 class="card-title"><b>Newsletter</b></h5>
              <form class="form-inline">
                <div class="form-group mb-2">
                  <label for="inputEmail2" class="sr-only">Email</label>
                  <input type="text" class="form-control" id="inputEmail2" placeholder="Email">
                </div>
                <div class="col-auto">
               <button type="button" class="btn btn-primary mb-2" onclick="location.href='interface'">Subscribe</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!--<footer class="small text-center text-muted">-->
        <!--    Website built by HM <a href="https://google.com/">linkedin</a>.-->
        <!--</footer>-->
      </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

user/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <!-- <div class="row"> -->
        <form method="POST" action="" class="form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4" style="text-align: center;">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                {{form.remember.label}}
                {{form.remember}}

            </fieldset>
            <div class="form-group" style="text-align: center;">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
                <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
                </small>
        </form>
    <!-- </div> -->
    <!-- <div class="row"> -->
        
    <!-- </div> -->
{% endblock content %}

user/templates/partners.html
{% extends "layout.html" %}
{% block content %}
    <h1>Partners Page</h1>
{% endblock content %}

user/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF - 8">
    <title>VIP User Profile</title>
</head>
<body>
    <h1>VIP User Profile</h1>
    <p>Welcome, {{ current_user.firstname }} {{ current_user.lastname }}</p>

</body>
</html>

user/templates/register.html
{% extends "layout.html" %}
{% block content %}
        <form method="POST" action="" class="form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Account</legend>
                <div class="form-group">
                    {{ form.firstname.label(class="form-control-label") }}

                    {% if form.firstname.errors %}
                        {{ form.firstname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.firstname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.firstname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.lastname.label(class="form-control-label") }}

                    {% if form.lastname.errors %}
                        {{ form.lastname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.lastname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.lastname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already Have An Account? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
                    </small>
                </div>
        </form>


{% endblock content %}

user/templates/select_products.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    {% for product in products %}
    

        <div class="col-sm">
	        <div class="card">
			  	<img src="/user/static/product{{ product.id }}.JPG" class="card-img-top" alt="...">
			  	<div class="card-body">
					<div>
						<b>
						{{ product.name }}
						</b>
					</div>					    
				    <p class="card-text">{{ product.description }}</p>
					<div id="addToCart">
						<a href="/addToCart/{{product.id}}">Add to cart</a>
					</div>
        		</div>
			</div>
		</div>

	
            


    {% endfor %}
</div>
{% endblock content %}

user/templates/unwrap-project.html
{% extends "layout.html" %}


{% block content %}

<div class="container">
    <div class="row">
        <h1>The Unwrap Project</h1>
        <img src="{{ url_for('user.static', filename='pic1.JPG') }}" class="d-block w-100" alt="...">
        <h1>
            <p>We grew up with the wrong recycling idea!</p>
        </h1>
        <h3><p>Our health and our bay are in danger. Plastic is toxic. </p></h3>

        <p>Every piece of plastic ever produced is still here, on landfills, in the ocean, but also in the air we breath, the water we drink, in the animals and plants we eat and the ground we leave on. </p>
        
        <div>  
        <img width="100%" src= "{{ url_for('user.static', filename='pic8.JPG') }}"  />
        </div>
        <div >  
        <h1>
            <p >So let's act and reduce our plastic consumption!</p>
        </h1>
        </div>
        <p>Our goal is to ease the transition to a plastic-free living in the great LA area. Our solution is to offer alternatives to our community and partner with brands that want and are ready to give alternatives.</p>
        <p>We want to keep it <b> easy, clean and accessible.</b> Our First step is Refill@home. A customizable "box" of locally made products in locally made containers that we can refill. Our ultimate goal is to open a physical spot in LA for plastic concerned customers. </p>

<!--TODO-->
      
        <h1>
        <p>Our Partners</p>
        </h1>
        <h5>
        <p>We’ve talked to many suppliers and curated the ones that had both great products and the will to sell in bulk to reduce packaging. </p>
        </h5>
        <h4><b>Our partners are curated through 4 main criteria:</b></h4>

            



        <ul style="list-style-type:none;">
            <li>Sustainable materials/ingredients</li>
            <li>Great quality</li>
            <li>Packaged-free (supplied in bulk) or at least plastic-free</li>
            <li>Local first</li>
        </ul>

        <!-- <h1>
            <p>The Founders</p>
        </h1> -->
    </div>
</div>



{% endblock content %}